version: '3'

services:
  grafana:
    image: grafana_example:v2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - grafana
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monitoring
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  monitoring:
    driver: bridge